apiVersion: v1
kind: Service
metadata:
  name: nginx-svc2
spec:
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
      nodePort: 30001
    - name: multitool
      port: 9002
      targetPort: 8080
      nodePort: 30002
  selector:
    app: nginx
  type: NodePort