apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-3
  labels:
    app: deployment-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-3
  template:
    metadata:
      labels:
        app: deployment-3
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
      initContainers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c", "nslookup service-2.default.svc.cluster.local"]